language: ruby
script: rspec spec

install:
  - gem update bundler

rvm:
  - 1.8
  - 1.9
  - 2.0
  - 2.1
  - jruby-18mode
  - jruby-19mode
  - ree

  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

env:
  global:
    - VERBOSE=true
    - TIMEOUT=1

branches:
  only:
    - master

notifications:
  email:
    - adamluzsi@gmail.com
