language: ruby

rvm:
  - 2.2.x
  - 2.1.x
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - jruby-18mode
  - jruby-19mode
  - rbx-2
  - ree

# gemfile: ".travis/Gemfile"

script: rspec spec

sudo: false

branches:
  only:
    - master

notifications:
  email:
    - adamluzsi@gmail.com
