language: ruby

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - jruby-18mode
  - jruby-19mode
  - rbx-2

gemfile: ".travis/Gemfile"

sudo: false

env:
  global:
    - VERBOSE=true
    - TIMEOUT=1

branches:
  only:
    - master

  allow_failures:
    - rvm: rbx-2

notifications:
  email:
    - adamluzsi@gmail.com
