language: ruby


rvm:
  - 1.8
  - 1.9
  - 2.0
  - 2.1
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - rbx-2
  - ree

env:
  global:
    - VERBOSE=true
    - TIMEOUT=1

# gemfile: ".travis/Gemfile"

script: rspec spec

sudo: false

branches:
  only:
    - master

notifications:
  email:
    - adamluzsi@gmail.com
