language: ruby


rvm:
  - 1.8.6
  - 1.8.7
  - 1.9.1
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.1.2
  - 2.1-head
  - jruby-18mode
  - jruby-19mode
  - rbx-2
  - ree


env:
  global:
    - VERBOSE=true
    - TIMEOUT=1

# gemfile: ".travis/Gemfile"

script: rspec spec

sudo: false

branches:
  only:
    - master

notifications:
  email:
    - adamluzsi@gmail.com
